// scripts/seed-usda.mjs
// Downloads USDA FoodData Central bulk CSV, verifies SHA-256, emits
// a supabase migration file with multi-row INSERT batches.
//
// Usage: node scripts/seed-usda.mjs
//
// Source: https://fdc.nal.usda.gov/download-datasets/
// License: CC0 1.0 (public domain). See https://fdc.nal.usda.gov/about-us.
//
// Run once when initially seeding and when refreshing USDA data annually.
// The generated SQL migration is committed so Supabase migrations remain
// offline-reproducible.

import { createHash } from 'node:crypto';
import {
  createReadStream,
  createWriteStream,
  writeFileSync,
  readFileSync,
  existsSync,
  unlinkSync,
} from 'node:fs';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import AdmZip from 'adm-zip';
import { parse } from 'csv-parse/sync';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const HASH_FILE = path.join(__dirname, '.usda-csv.sha256');
const OUT_MIGRATION = path.resolve(
  __dirname,
  '../supabase/migrations/20260425003002_seed_nutrition_facts.sql'
);

const USDA_CSV_URL =
  'https://fdc.nal.usda.gov/fdc-datasets/FoodData_Central_foundation_food_csv_2024-04-18.zip';
// For SR Legacy, fetch:
// https://fdc.nal.usda.gov/fdc-datasets/FoodData_Central_sr_legacy_food_csv_2018-04.zip

// The macro columns come from food_nutrient.csv joined to nutrient.csv on:
//   kcal:        1008 (Energy, KCAL)
//   protein_g:   1003
//   fat_g:       1004
//   carbs_g:     1005
//   fiber_g:     1079

const NUTRIENT_IDS = {
  kcal: 1008,
  protein_g: 1003,
  fat_g: 1004,
  carbs_g: 1005,
  fiber_g: 1079,
};

const SOURCE_LABEL = 'foundation';

async function download(url, outPath) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Download failed: ${res.status} ${res.statusText}`);
  await pipeline(Readable.fromWeb(res.body), createWriteStream(outPath));
}

function sha256(filePath) {
  return new Promise((resolve, reject) => {
    const hash = createHash('sha256');
    createReadStream(filePath)
      .on('data', (chunk) => hash.update(chunk))
      .on('end', () => resolve(hash.digest('hex')))
      .on('error', reject);
  });
}

function sqlEscape(s) {
  return String(s).replace(/'/g, "''");
}

function emitBatchedInserts(rows, batchSize = 500) {
  const header =
    `-- Generated by scripts/seed-usda.mjs. Do not hand-edit.\n` +
    `-- Source: USDA FoodData Central (CC0). See scripts/.usda-csv.sha256.\n\n`;
  let out = header;
  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize);
    out += 'insert into nutrition_facts (fdc_id, name, kcal, protein_g, fat_g, carbs_g, fiber_g, source) values\n';
    out += batch
      .map(
        (r) =>
          `  (${r.fdc_id}, '${sqlEscape(r.name)}', ${r.kcal}, ${r.protein_g}, ${r.fat_g}, ${r.carbs_g}, ${r.fiber_g}, '${r.source}')`
      )
      .join(',\n');
    out += '\non conflict (fdc_id) do update set\n';
    out +=
      '  name = excluded.name,\n' +
      '  kcal = excluded.kcal,\n' +
      '  protein_g = excluded.protein_g,\n' +
      '  fat_g = excluded.fat_g,\n' +
      '  carbs_g = excluded.carbs_g,\n' +
      '  fiber_g = excluded.fiber_g,\n' +
      '  source = excluded.source;\n\n';
  }
  return out;
}

function parseZip(zipPath) {
  const zip = new AdmZip(zipPath);
  const entries = zip.getEntries();
  const byName = {};
  for (const entry of entries) {
    const base = path.basename(entry.entryName);
    if (base === 'food.csv' || base === 'food_nutrient.csv') {
      byName[base] = entry.getData().toString('utf8');
    }
  }
  if (!byName['food.csv'] || !byName['food_nutrient.csv']) {
    throw new Error('USDA ZIP missing expected files food.csv / food_nutrient.csv');
  }
  return byName;
}

function buildRows(foodCsv, foodNutrientCsv) {
  const foods = parse(foodCsv, { columns: true, skip_empty_lines: true, relax_column_count: true });
  const nutrients = parse(foodNutrientCsv, {
    columns: true,
    skip_empty_lines: true,
    relax_column_count: true,
  });

  const foodById = new Map();
  for (const f of foods) {
    const fdcId = Number(f.fdc_id);
    if (!Number.isFinite(fdcId)) continue;
    foodById.set(fdcId, {
      fdc_id: fdcId,
      name: (f.description ?? '').trim(),
      source: SOURCE_LABEL,
      kcal: 0,
      protein_g: 0,
      fat_g: 0,
      carbs_g: 0,
      fiber_g: 0,
      matched: new Set(),
    });
  }

  const wantedIds = new Set(Object.values(NUTRIENT_IDS));
  for (const n of nutrients) {
    const fdcId = Number(n.fdc_id);
    const nutrientId = Number(n.nutrient_id);
    if (!wantedIds.has(nutrientId)) continue;
    const food = foodById.get(fdcId);
    if (!food) continue;
    const amount = Number(n.amount);
    if (!Number.isFinite(amount)) continue;
    for (const [k, id] of Object.entries(NUTRIENT_IDS)) {
      if (id === nutrientId) {
        food[k] = amount;
        food.matched.add(k);
      }
    }
  }

  const rows = [];
  for (const food of foodById.values()) {
    if (!food.name) continue;
    if (!food.matched.has('kcal')) continue;
    delete food.matched;
    rows.push(food);
  }
  return rows;
}

async function main() {
  const tmpZip = path.join(__dirname, '.usda-tmp.zip');
  console.log(`Downloading ${USDA_CSV_URL} ...`);
  await download(USDA_CSV_URL, tmpZip);

  const actualHash = await sha256(tmpZip);
  if (existsSync(HASH_FILE)) {
    const expected = readFileSync(HASH_FILE, 'utf8').trim();
    if (expected && expected !== actualHash) {
      throw new Error(
        `SHA-256 mismatch.\n  expected: ${expected}\n  actual:   ${actualHash}\n` +
          `If USDA intentionally updated the dataset, replace scripts/.usda-csv.sha256 with the new hash.`
      );
    }
  } else {
    writeFileSync(HASH_FILE, actualHash + '\n', 'utf8');
    console.log(`Recorded new hash in ${HASH_FILE}: ${actualHash}`);
  }

  const csvs = parseZip(tmpZip);
  const rows = buildRows(csvs['food.csv'], csvs['food_nutrient.csv']);

  const sql = emitBatchedInserts(rows);
  writeFileSync(OUT_MIGRATION, sql, 'utf8');
  console.log(`Wrote ${rows.length} rows to ${OUT_MIGRATION}`);

  try {
    unlinkSync(tmpZip);
  } catch {}
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
