create table ingredient_count_weights (
  name        text primary key,
  g_per_item  numeric not null
);

alter table ingredient_count_weights enable row level security;

create policy ingredient_count_weights_authenticated_read
  on ingredient_count_weights for select
  to authenticated
  using (true);

-- Hand-curated seed. Sources: USDA FDC typical serving weights + culinary reference.
insert into ingredient_count_weights (name, g_per_item) values
  ('egg',                 50),
  ('egg yolk',            18),
  ('egg white',           33),
  ('garlic clove',        5),
  ('garlic head',         50),
  ('onion',               150),
  ('red onion',           150),
  ('yellow onion',        150),
  ('white onion',         150),
  ('shallot',             30),
  ('green onion',         15),
  ('scallion',            15),
  ('leek',                90),
  ('tomato',              123),
  ('roma tomato',         60),
  ('cherry tomato',       17),
  ('plum tomato',         60),
  ('potato',              170),
  ('russet potato',       213),
  ('red potato',          170),
  ('sweet potato',        130),
  ('yukon gold potato',   170),
  ('carrot',              60),
  ('baby carrot',         10),
  ('celery stalk',        40),
  ('celery rib',          40),
  ('bell pepper',         120),
  ('red bell pepper',     120),
  ('green bell pepper',   120),
  ('yellow bell pepper',  120),
  ('jalapeño',            14),
  ('jalapeno',            14),
  ('serrano pepper',      7),
  ('habanero',            8),
  ('poblano',             60),
  ('thai chili',          3),
  ('lemon',               65),
  ('lime',                45),
  ('orange',              130),
  ('grapefruit',          230),
  ('apple',               180),
  ('pear',                180),
  ('banana',              120),
  ('avocado',             200),
  ('mango',               200),
  ('pineapple',           900),
  ('kiwi',                75),
  ('peach',               150),
  ('plum',                70),
  ('cucumber',            300),
  ('english cucumber',    400),
  ('zucchini',            200),
  ('yellow squash',       200),
  ('eggplant',            460),
  ('butternut squash',    900),
  ('acorn squash',        500),
  ('artichoke',           120),
  ('corn cob',            125),
  ('mushroom',            18),
  ('button mushroom',     18),
  ('cremini mushroom',    20),
  ('portobello mushroom', 85),
  ('shiitake mushroom',   15),
  ('bay leaf',            0.2),
  ('bread slice',         30),
  ('tortilla',            30),
  ('flour tortilla',      50),
  ('corn tortilla',       25),
  ('pita',                60),
  ('english muffin',      57),
  ('bacon slice',         12),
  ('bacon strip',         12),
  ('prosciutto slice',    10),
  ('ham slice',           28),
  ('salami slice',        5),
  ('chicken breast',      174),
  ('chicken thigh',       100),
  ('chicken wing',        90),
  ('chicken leg',         150),
  ('chicken drumstick',   110),
  ('hamburger patty',     113),
  ('burger patty',        113),
  ('sausage link',        75),
  ('hot dog',             45),
  ('meatball',            30),
  ('shrimp',              6),
  ('scallop',             15),
  ('oyster',              15),
  ('mussel',              8),
  ('clam',                12),
  ('fig',                 40),
  ('date',                7),
  ('apricot',             35),
  ('strawberry',          12),
  ('raspberry',           2),
  ('blueberry',           1),
  ('blackberry',          2);
