import type { OAuthHelpers } from '@cloudflare/workers-oauth-provider';

/**
 * Worker bindings + secrets. MCP_OBJECT, OAUTH_KV, APP_BASE_URL come from
 * Cloudflare.Env (generated by `wrangler types` from wrangler.jsonc). Here we add
 * the OAuth helper injected at runtime and the secrets (set via `wrangler secret put`).
 */
export interface Env extends Cloudflare.Env {
  OAUTH_PROVIDER: OAuthHelpers;
  SUPABASE_URL: string;
  SUPABASE_ANON_KEY: string;
  COOKIE_ENCRYPTION_KEY: string;
}
